In [11]:
import pandas as pd
#import matplotlib.ticker as mtick
import numpy as np

In [12]:
df1=pd.read_csv ('results/K12_Enrollment_public_MAZ.csv')
df2=pd.read_csv ('results/privK12_Enrollment_MAZ.csv')

# Combine them row-wise (default axis=0)
df_combined = pd.concat([df1, df2], ignore_index=True)
display (df_combined)

,maz_id,SchoolName,Public_Elem,Public_Midl,Public_High,PriCha_Elem,PriCha_Midl,PriCha_High,Enrol_Elem,Enrol_Midl,Enrol_High,PINST
0,44,Goldminer's Daughter,11.0,0.0,0.0,0.0,0.0,0.0,11,0,0,NaN
1,6818,Summit Academy - Bluffdale,0.0,0.0,0.0,537.0,0.0,0.0,537,0,0,NaN
2,6858,Blackridge School,782.0,0.0,0.0,0.0,0.0,0.0,782,0,0,NaN
3,6859,Ridge View Elementary,713.0,0.0,0.0,0.0,0.0,0.0,713,0,0,NaN
4,6862,Oak Hollow School,488.0,0.0,0.0,0.0,0.0,0.0,488,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
898,31228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,9,0,PROVO CANYON SCHOOL-PROVO CAMPUS
899,31836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,62,DISCOVERY ACADEMY
900,32140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,111,THE HERRITAGE SCHOOL
901,32169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75,0,0,KIDS VILLAGE
902,32249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,34,NEW HAVEN SCHOOL

In [13]:
# Group by CO_TAZID and sum the enrollment columns
df_grouped = df_combined.groupby('maz_id', as_index=False)[['Enrol_Elem', 'Enrol_Midl', 'Enrol_High']].sum()

display(df_grouped)

     maz_id  Enrol_Elem  Enrol_Midl  Enrol_High
0        44          11           0           0
1      6818         537           0           0
2      6858         782           0           0
3      6859         713           0           0
4      6862         488           0           0
..      ...         ...         ...         ...
833   32163           0           0        3325
834   32169          75           0           0
835   32249           0           0          34
836   32309           0           0           0
837   32370           0          19         216

[838 rows x 4 columns]

In [14]:
#export CO_TAZID enrollment to csv

df_grouped.to_csv("results\GroupedEnrollmentByTAZ06252026.csv", index=False)
# Calculate totals one by one
total_elem = df_grouped['Enrol_Elem'].sum()
total_midl = df_grouped['Enrol_Midl'].sum()
total_high = df_grouped['Enrol_High'].sum()

print(f"Total Elementary Enrollment: {total_elem}")
print(f"Total Middle School Enrollment: {total_midl}")
print(f"Total High School Enrollment: {total_high}")

Total Elementary Enrollment: 243914
Total Middle School Enrollment: 113294
Total High School Enrollment: 134011

In [15]:

df_grouped=pd.read_csv(r"C:\FFcalibV10_CVM\WF-TDM-Development-v1000CVM\1_Inputs\2_SEData\SE_Static.csv")
# Calculate totals one by one
total_elem = df_grouped['Enrol_Elem'].sum()
total_midl = df_grouped['Enrol_Midl'].sum()
total_high = df_grouped['Enrol_High'].sum()

print(f"Total Elementary Enrollment: {total_elem}")
print(f"Total Middle School Enrollment: {total_midl}")
print(f"Total High School Enrollment: {total_high}")

Total Elementary Enrollment: 242885
Total Middle School Enrollment: 113872
Total High School Enrollment: 133881